### ISSUE TITLE
[Bug] Dupe Glitch

### ISSUE THREAD

**Issue by xMikey** [SoulLength/PortableChests#3]
- Plugin version Latest
- Minecraft version 1.17
- Server type Paper

Not sure if this is relevant or something fixable or even this plugins fault but I wanted to point out that
If you combine the plugin [DeadChest](https://dev.bukkit.org/projects/dead-chest) with this plugin it creates the possibility to dupe, because if you place a container holding items next to an active deadchest it breaks the chest dropping the items however the chest also goes back into inventory holding the original items.

**Comment by SoulLength** [comment]
It was a priority problem, the BlockPlacedEvent in my plugin was being executed before it could be canceled by DeadChest's BlockPlacedEvent.
Changing the event priority fixed the issue.

Thanks!
