### ISSUE TITLE
[Bug] Colored shulker Boxes still apply penalties

### ISSUE THREAD

**Issue by ASlicedBreaad** [SoulLength/PortableChests#6]
Regular Shulker boxes don't apply any penalties but any other colored one does

**Comment by SoulLength** [comment]
Just deployed a new release which doesn't fix this bug yet, i will fix it in the next release, thanks for reporting it!

**Comment by SoulLength** [comment]
Bug fixed in the [new release](https://github.com/SoulLength/PortableChests/releases/tag/1.5.4)
